# To override the docker-compose file use this command :
# $ docker-compose -f docker-compose.yml -f docker/docker-production.yml up -d

db:
  restart: always
app:
  command: bundle exec puma -C /myapp/config/puma.rb -p 3000 -e production
  restart: always

# the dockerfile to mount the image is in ./docker/container/nginx
nginx:
  build: ./docker/container/nginx
  links:
    - app
  ports:
    - "80:80"
  restart: always
