# is it usefull yet to have 2 different config between prod and dev if the goal is to have the most near config between both? The password is still save in env

development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
